export const zhuboState = {
  bid: null,
  contentScore: null,
  departmentID: null,
  effectScore: null,
  flower: null,
  info: null,
  intro: null,
  methodScore: null,
  nickname: null,
  p_40: null,
  p_150: null,
  p_260: null,
  partner_id: null,
  portraitUpdate: null,
  role: null,
  scoreConfig: {},
  scoreIcon: null,
  scoreNum: null,
  scoreTotal: null,
  scoreType: null,
  showScore: null,
  sid: null,
  status: null,
};
