export const UPDATE_TOKEN = "UPDATE_TOKEN" // token
export const UPDATE_WHITEBOARD_VERSION = "UPDATE_WHITEBOARD_VERSION" // UPDATE_WHITEBOARD_VERSION
export const UPDATE_WHITEBOARD_PAGE = 'UPDATE_WHITEBOARD_PAGE' // UPDATE_WHITEBOARD_PAGE
export const UPDATE_INIT_DATA = "UPDATE_INIT_DATA" // initData
export const UPDATE_LIVE_DATA = "UPDATE_LIVE_DATA" // liveData
export const UPDATE_LIVE_MODE = "UPDATE_LIVE_MODE" // live mode change
export const UPDATE_LIVE_STATUS = "UPDATE_LIVE_STATUS" //video state
export const UPDATE_TECH_ORDER = 'UPDATE_TECH_ORDER' //tech order
export const UPDATE_CAMERA_DOM = 'UPDATE_CAMERA_DOM' //camera-dom
export const UPDATE_LOOP_MODE = 'UPDATE_LOOP_MODE' // loop mode
export const UPDATE_VIDEO_DOM = 'UPDATE_VIDEO_DOM' //video/desktop-dom
export const UPDATE_MEDIA_DOM = 'UPDATE_MEDIA_DOM' // media dom single stream
export const UPDATE_WHITEBOARD_DOM = 'UPDATE_WHITEBOARD_DOM' //whiteboard-dom
export const UPDATE_API_DOMAIN = 'UPDATE_API_DOMAIN' //update api domain
export const UPDATE_EXT_CONFIG = 'UPDATE_EXT_CONFIG' //update ext config
export const UPDATE_STEP_DATA = 'UPDATE_STEP_DATA' //update step data
export const UPDATE_FULLSCREEN_STATE = 'UPDATE_FULLSCREEN_STATE' //update fullscreen
export const UPDATE_LIVE_STATE = 'UPDATE_LIVE_STATE' //update UPDATE_LIVE_STATE