/* member模块 */
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST'
export const UPDATE_ONLINE_XIDS = 'UPDATE_ONLINE_XIDS'
export const DELETE_ONLINE_XIDS = 'DELETE_ONLINE_XIDS'
export const UPDATE_ROBOTLIST_OBJ = 'UPDATE_ROBOTLIST_OBJ'
export const UPDATE_GROUP = 'UPDATE_GROUP'

// question
export const ADD_QUESTION_ID = 'ADD_QUESTION_ID'
export const DELETE_QUESTION_ID = 'DELETE_QUESTION_ID'

// room
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const UPDATE_APP_HOST = 'UPDATE_APP_HOST';
export const UPDATE_CON_STRING = 'UPDATE_CON_STRING';
export const UPDATE_HEARTBEAT_INTERVAL = 'UPDATE_HEARTBEAT_INTERVAL';
export const UPDATE_LIVE = 'UPDATE_LIVE';
export const UPDATE_MODULES = 'UPDATE_MODULES';
export const UPDATE_PLUGIN = 'UPDATE_PLUGIN';
export const UPDATE_RTMP = 'UPDATE_RTMP';
export const UPDATE_CUR_USER = 'UPDATE_CUR_USER';
export const UPDATE_ZHUBO = 'UPDATE_ZHUBO';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_WEBSOCKET = 'UPDATE_WEBSOCKET';
export const UPDATE_CAMERA_URL = 'UPDATE_CAMERA_URL';
export const UPDATE_SWF_URL = 'UPDATE_SWF_URL';
export const UPDATE_LIVING_DURATION = 'UPDATE_LIVING_DURATION';
export const UPDATE_ANNOUNCE = 'UPDATE_ANNOUNCE';
export const UPDATE_FLASHVAR = 'UPDATE_FLASHVAR';
export const UPDATE_INIT_EVENT = 'UPDATE_INIT_EVENT';
export const UPDATE_MODE_TYPE = 'UPDATE_MODE_TYPE';
export const UPDATE_LIVE_PLAYER_URL = 'UPDATE_LIVE_PLAYER_URL';
export const UPDATE_RES_CONFIG = 'UPDATE_RES_CONFIG';
export const UPDATE_ROBOTS = 'UPDATE_ROBOTS';
export const UPDATE_ROOM_MODULES = 'UPDATE_ROOM_MODULES';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_USER_CAMERA = 'UPDATE_USER_CAMERA';
export const UPDATE_EXT = 'UPDATE_EXT';
export const UPDATE_ONLINE = 'UPDATE_ONLINE';
export const UPDATE_LIVE_STATUS = 'UPDATE_LIVE_STATUS'
export const UPDATE_EXTENSION_CONFIG = 'UPDATE_EXTENSION_CONFIG';
export const UPDATE_INIT_DATA = 'UPDATE_INIT_DATA';
export const UPDATE_LIVE_MODE = 'UPDATE_LIVE_MODE';
export const UPDATE_LIVE_DATA = 'UPDATE_LIVE_DATA';
export const UPDATE_LIVE_STATE = 'UPDATE_LIVE_STATE';
export const UPDATE_LOOP_MODE = 'UPDATE_LOOP_MODE';
export const UPDATE_WEBFULLSCREEN_OTHER = 'UPDATE_WEBFULLSCREEN_OTHER'

// media
export const UPDATE_MEDIA_STATUS = 'UPDATE_MEDIA_STATUS';
export const UPDATE_TECH_ORDER = 'UPDATE_TECH_ORDER';
export const UPDATE_MEDIA_DOM = 'UPDATE_MEDIA_DOM';
export const UPDATE_VIDEO_DOM = 'UPDATE_VIDEO_DOM';
export const UPDATE_CAMERA_DOM = 'UPDATE_CAMERA_DOM';
export const UPDATE_STEP_DATA = 'UPDATE_STEP_DATA'
export const UPDATE_FULLSCREEN_STATE = 'UPDATE_FULLSCREEN_STATE'; // 更新真全屏的状态
export const UPDATE_VIDEO_WEB_FULLSCREEN_STATE = 'UPDATE_VIDEO_WEB_FULLSCREEN_STATE' // 更新桌面分享/视频的网页全屏状态
export const UPDATE_CAMERA_WEB_FULLSCREEN_STATE = 'UPDATE_CAMERA_WEB_FULLSCREEN_STATE' // 更新摄像头的网页全屏状态


// zhubo 
export const UPDATE_BID = 'UPDATE_BID';
export const UPDATE_CONTENT_SCORE = 'UPDATE_CONTENT_SCORE';    
export const UPDATE_DEPARTMENT_I_D = 'UPDATE_DEPARTMENT_I_D';  
export const UPDATE_EFFECT_SCORE = 'UPDATE_EFFECT_SCORE';      
export const UPDATE_FLOWER = 'UPDATE_FLOWER';
export const UPDATE_INFO = 'UPDATE_INFO';
export const UPDATE_INTRO = 'UPDATE_INTRO';
export const UPDATE_METHOD_SCORE = 'UPDATE_METHOD_SCORE';      
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME';
export const UPDATE_P_40 = 'UPDATE_P_40';
export const UPDATE_P_150 = 'UPDATE_P_150';
export const UPDATE_P_260 = 'UPDATE_P_260';
export const UPDATE_PARTNER_ID = 'UPDATE_PARTNER_ID';
export const UPDATE_PORTRAIT_UPDATE = 'UPDATE_PORTRAIT_UPDATE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_SCORE_CONFIG = 'UPDATE_SCORE_CONFIG';
export const UPDATE_SCORE_ICON = 'UPDATE_SCORE_ICON';
export const UPDATE_SCORE_NUM = 'UPDATE_SCORE_NUM';
export const UPDATE_SCORE_TOTAL = 'UPDATE_SCORE_TOTAL';
export const UPDATE_SCORE_TYPE = 'UPDATE_SCORE_TYPE';
export const UPDATE_SHOW_SCORE = 'UPDATE_SHOW_SCORE';
export const UPDATE_SID = 'UPDATE_SID';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const MERGE_STATE = 'MERGE_STATE'

// whiteboard
export const UPDATE_WHITEBOARD_DOM = 'UPDATE_WHITEBOARD_DOM';
export const UPDATE_WHITEBOARD_VERSION = 'UPDATE_WHITEBOARD_VERSION';
export const UPDATE_WHITEBOARD_PAGE = 'UPDATE_WHITEBOARD_PAGE';
export const UPDATE_WHITEBOARD_WEB_FULLSCREEN_STATE = 'UPDATE_WHITEBOARD_CAMERA_WEB_FULLSCREEN_STATE' // 更新课件的网页全屏状态

// network
export const UPDATE_NETWORK_SPEED = 'UPDATE_NETWORK_SPEED'